---
driver_plugin: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  attributes:
    bamboo:
      database:
        version: '5.5'
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[bamboo]
    attributes:
      bamboo:
        jvm:
          minimum_memory: '64m'
        name: bamboo-dev
        backup:
          enabled: false
          ceph: false
        agent:
          data_dir: /var/bamboo-agent
          home_dir: /opt/bamboo-agent
  - name: mysql-56
    run_list:
      - recipe[bamboo]
    attributes:
      bamboo:
        jvm:
          minimum_memory: '64m'
        database:
          name: 'db1'
          type: 'mysql'
          version: '5.6'
