AllCops:
  Exclude:
    - test/**
    - vendor/**/*
    - spec/**
Documentation:
  Enabled: false
AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
#
# we like our neatly-aligned code too much
#
SingleSpaceBeforeFirstArg:
  Enabled: false
#
# group of `depends` have some lone lines that we want aligned to group
#
ExtraSpacing:
  Exclude:
    - metadata.rb
#
# couldn't figure it out so set this
#
ClassAndModuleChildren:
  EnforcedStyle: compact

#
# libraries/bamboo is to complex for rubocop
#
Metrics/AbcSize:
 Max: 17
